export const patch = {
  'addOption': ' إضافة خيار',
  'allFieldsRemoved': ' تمّت إزالة جميع المجالات..',
  'allowSelect': 'السماح بالإختيار',
  'autocomplete': 'الإكمال التلقائي',
  'button': ' زر',
  'cannotBeEmpty': ' هذه المعلومة لا يمكن أن تكون فارغة',
  'checkboxGroup': 'مجموعة اختيارات متعددة',
  'checkbox': ' خانة الاختيار',
  'checkboxes': 'خانات اختيار',
  'class': ' صنف',
  'clearAllMessage': 'هل أنت متأكد أنك تريد مسح كافة المعلومات؟',
  'clear': 'إفسخ',
  'close': 'أغلق',
  'content': 'محتوى',
  'copy': 'نسخ إلى الحافظة',
  'dateField': 'حقل تاريخ',
  'description': 'نص المساعدة',
  'descriptionField': 'وصف',
  'devMode': 'وضع المطور',
  'editNames': 'تغيير الأسماء',
  'editorTitle': 'عناصر النموذج',
  'editXML': 'تحرير XML',
  'fieldDeleteWarning': ' خاطئة',
  'fieldVars': 'متغيّرات الحقل',
  'fieldNonEditable': 'هذا الحقل لا يمكن تعديله.',
  'fieldRemoveWarning': ' هل حقا تريد حذف هذا المجال؟',
  'fileDocuments': 'تحميل الملف',
  'formUpdated': 'تّم تحديث الإستمارة',
  'getStarted': 'اسحب من اليمين إلى هذه المنطقة',
  'header': 'رأس الصفحة',
  'hide': ' تحديث',
  'hidden': ' الإدخال مخفي',
  'label': ' التسمية',
  'labelEmpty': 'التسمية لا يمكن أن يكون فارغا',
  'limitRole': 'تقييد الوصول إلى واحد أو أكثر من الأدوار التالية:',
  'mandatory': 'إلزامي',
  'max': 'أعلى قيمة',
  'maxlength': ' أقصى طول ',
  'min': 'أقل قيمة',
  'minOptionMessage': 'يتطلب هذا المجال لا تقل عن 2 خيارات',
  'name': 'الاسم',
  'number': 'حقل رقمي',
  'no': 'لا',
  'off': ' غير مفعل',
  'on': 'مفعل',
  'option': 'اختيار',
  'optional': ' اختياري',
  'optionEmpty': 'قيمة الخيار المطلوبة',
  'paragraph': 'فقرة',
  'placeholder': 'العنصر النائب',
  'placeholder.value': 'القيمة',
  'placeholder.label': ' تسمية',
  'placeholder.text': 'أدخل بعض النص',
  'placeholder.textarea': ' إدخال الكثير من النص',
  'placeholder.email': ' أدخل البريد الإلكتروني',
  'placeholder.placeholder': 'العنصر النائب',
  'placeholder.className': 'فئات مفصولة بمسافات',
  'placeholder.password': 'أدخل كلمة المرور',
  'preview': 'المعاينة',
  'radioGroup': 'مجموعة اختيارات فردية',
  'radio': ' اختيار',
  'removeMessage': ' إزالة عنصر',
  'remove': '&#215;',
  'required': ' إجبارية',
  'richText': ' محرر WYSIWYG',
  'roles': 'وصول',
  'save': 'حفظ',
  'selectOptions': 'خيارات',
  'select': 'قائمة اختيارات',
  'selectColor': 'اختيار اللون',
  'selectionsMessage': 'سماح اختيارات متعددة',
  'size': 'حجم',
  'sizes': 'الأحجام',
  'sizes.xs': 'صغيرة اضافية',
  'sizes.sm': 'صغير',
  'sizes.m': 'تبعا للإعدادات الافتراضية',
  'sizes.lg': ' كبير',
  'style': 'شكل',
  'styles': 'الأشكال',
  'styles.btn': 'شكل الزر',
  'styles.btn.default': 'تبعا للإعدادات الافتراضية',
  'styles.btn.danger': 'خطر',
  'styles.btn.info': 'معلومات',
  'styles.btn.primary': 'أساسي',
  'styles.btn.success': 'نجاح',
  'styles.btn.warning': 'إعلام',
  'subtype': 'نوع',
  'text': 'حقل نصي',
  'textArea': 'مساحة نصية',
  'toggle': 'نوع التبديل',
  'warning': 'تحذير!',
  'viewXML': '</>',
  'viewJSON': '{ }',
  'yes': 'نعم'
};
